apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
  apiVersion: v1
  kind: Service
  metadata:
    name: influxdb
  spec:
    type: ClusterIP
    ports:
    - port: 8086
      targetPort: 8086
    selector:
      app: influxdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  serviceName: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb
        imagePullPolicy: Never
        volumeMounts:
          - name: influxdb-pv
            mountPath: /var/lib/influxdb
        ports:
        - containerPort: 8086
      volumes:
        - name: influxdb-pv
          persistentVolumeClaim:
            claimName: influxdb-pv-claim